### ISSUE TITLE
Go Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#1]
_From @fabusard on February 8, 2017 18:34_

When the user clicks the Go Button under the search bars on the main page, the recipes listed on the main page will be filtered based on the recipe name and/or ingredients they entered. 

When the user clicks the Go Button under the search bars on the favourite recipes page, their list of favourite recipes will be filtered based on the recipe name and/or ingredients they entered.

_Copied from original issue: poisonctrl/G7#1_

**Comment by ghost** [comment]
The user can press on “Search by Ingredient” or ”Search by Recipename” to search the database by ingredient or recipe name  respectively.

**Comment by ghost** [comment]
Work on this feature will continue during stage 3 until the desired user story is achieved.

**Comment by nathandinatale** [comment]
The Go button is now implemented into two separate search buttons, one for recipes and one for ingredients.
