### ISSUE TITLE
LogOutButton

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#10]
_From @AllanRK on February 8, 2017 21:12_

While the user is logged in, a button to logout will be visible. 

Once clicked, the user will be logged out of their account and be unable to change any settings on their account. The logout button will also be changed to a Login button. The profile button will change to sign-up. The page will reload.

_Copied from original issue: poisonctrl/G7#10_

**Comment by poisonctrl** [comment]
Assigned to AllanRK per request in Slack #meetinglog

**Comment by poisonctrl** [comment]
Replaced text from .md file.  As comment was blank.

Added the change of the profile button.

**Comment by nathandinatale** [comment]
Omitted by the TA after stage 2.
