### ISSUE TITLE
Homebutton

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#11]
_From @leikites on February 8, 2017 21:32_

When the user clicks on the home button they will go back in the website's main page. 

If the user is not logged in, they will see sign-up and login buttons.  If they are logged in they will see favourite and add recipe options, as well, the sign-up and login buttons are replaced by profile and logout.

_Copied from original issue: poisonctrl/G7#11_

**Comment by poisonctrl** [comment]
Reviewed and edited to reflect perspective of anonymous user vs authenticated user.

**Comment by nathandinatale** [comment]
No longer required, everything happens on the same page.
