### ISSUE TITLE
Signinbutton

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#12]
_From @leikites on February 8, 2017 21:33_

When the user clicks on the sign in button they will be presented with two empty fields where they will enter their username and password. 

They will be presented with the homepage. 

If their password is incorrect they will be presented with an error message.

_Copied from original issue: poisonctrl/G7#12_

**Comment by poisonctrl** [comment]
Updated to reflect removal of 6-digit code as this was deemed a secondary feature.

**Comment by poisonctrl** [comment]
API for this function is localhost:8080/login/auth to be actioned.

**Comment by nathandinatale** [comment]
Note: The button is now called "Login"
