### ISSUE TITLE
Sign Up Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#14]
_From @poisonctrl on February 9, 2017 18:36_

A user will enter a username and password and attempt to sign-up.

If the account is already created they will be notified.

If the account is not already created they will be redirected to their new home page. 

_Copied from original issue: poisonctrl/G7#14_

**Comment by nathandinatale** [comment]
Accounts can be manually created from the backend, but this has yet to be implemented in the UI.
