### ISSUE TITLE
Upload Recipe Button 

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#17]
_From @mdudycz on February 9, 2017 19:1_

The upload recipe button is found on the page the user is guided to, once selecting the add recipe button.

When pressed the information entered on the add recipe page will be saved to the database, and the user will be directed back to the home page. 

_Copied from original issue: poisonctrl/G7#17_

**Comment by nathandinatale** [comment]
Can be done through the backend but no current UI implementation
