### ISSUE TITLE
Favourite Recipes Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#2]
_From @fabusard on February 8, 2017 18:45_

When the user clicks the Favourite Recipes Button, they will be presented with a list of the recipes they have saved to their Favourite Recipes List.

They can click on each recipe in the list to get the detailed version of the recipe.

_Copied from original issue: poisonctrl/G7#2_

**Comment by poisonctrl** [comment]
Faisal assigned per request in Slack #meetinglog

**Comment by nathandinatale** [comment]
Omitted by the TA after stage 2.
