### ISSUE TITLE
Recipe Name Field

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#22]
_From @poisonctrl on February 10, 2017 18:18_

Users can enter the name of a recipe here, entries will be restricted to letters (upper and lower), numbers and specific characters.

_Copied from original issue: poisonctrl/G7#22_

**Comment by nathandinatale** [comment]
There are no restrictions to the recipe name field, the user may enter any sequence of characters

**Comment by nathandinatale** [comment]
This can be done via the backend, there are no restrictions to specific characters. No current UI implementation.
