### ISSUE TITLE
Ingredient Name Field

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#23]
_From @poisonctrl on February 10, 2017 18:20_

In this case an ingredient is broken into three parts Name is the first field.  All other add ingredient fields on the website will be used to search by ingredient name, but to display a recipe quantity and measure are important. 

_Copied from original issue: poisonctrl/G7#23_

**Comment by nathandinatale** [comment]
This can be done via the backend, there are no restrictions to specific characters. No current UI implementation.
