### ISSUE TITLE
Description Field

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#24]
_From @poisonctrl on February 10, 2017 18:21_

The description field is used to describe the steps in a recipe and general information about a recipe. 

_Copied from original issue: poisonctrl/G7#24_

**Comment by fabusard** [comment]
After the user searched the database by ingredient(s)/name they will receive a list of corresponding recipes each of which has the steps in a recipe and general information about a recipe.

**Comment by nathandinatale** [comment]
This can be done via the backend, there are no restrictions to specific characters. No current UI implementation.
