### ISSUE TITLE
Recipe Picture and Upload Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#25]
_From @poisonctrl on February 10, 2017 18:24_

While on the add recipe page. The user will click on the upload button to add a picture to their recipe.

Once clicked it will open that user’s computer explorer, and the user can select an image that will be saved and displayed on the recipe page and on the search results.

On the recipe page it will display in the recipe picture box.

_Copied from original issue: poisonctrl/G7#25_

**Comment by nathandinatale** [comment]
Omitted by the TA in Stage 2.
