### ISSUE TITLE
Add Ingredient Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#3]
_From @mapqlz on February 8, 2017 19:45_

When the user hits the add ingredient button, three boxes appear in which the user can enter in their ingredient quantity, measure and name as required by the recipe. 

Button has same look and feel in the search bar and adds an ingredient line to the search bar to add more entries to the search area. 

_Copied from original issue: poisonctrl/G7#3_

**Comment by poisonctrl** [comment]
Updated to reflect latest version of mock-up pictures.

**Comment by ghost** [comment]
The user can enter the name of the ingredient they want to add in the same field they would use to remove an ingredient. After that they can click on “Add Ingredient" to add it.

**Comment by ghost** [comment]
Work on this feature will continue during stage 3 until the desired user story is achieved.

**Comment by nathandinatale** [comment]
This feature can be done through the backend but there is currently no UI implementation.
