### ISSUE TITLE
Login and Sign up UI

### ISSUE THREAD

**Issue by ghost** [poisonctrl/FoodBookSQLDB#38]
Create UI components needed for user registration and login. This will be initiated when controllers for login and sign up are finished.

**Comment by poisonctrl** [comment]
API action button will be localhost:8080/login/auth for login, registration not functioning yet but should be /registration/ or something similar if we get it working.

**Comment by poisonctrl** [comment]
For final page post-login appearance of add recipe button must occur

**Comment by nathandinatale** [comment]
Signup can be done via the backend, UI for login has been implemented.
