### ISSUE TITLE
Remove Ingredient Button

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#4]
_From @mapqlz on February 8, 2017 19:47_

When the user clicks on the remove ingredient button beside a specific ingredient, that ingredient will be removed from the ingredients list required to make the recipe.

Button has same look and feel in the search bar and removes an ingredient line to the search bar.

_Copied from original issue: poisonctrl/G7#4_

**Comment by ghost** [comment]
The user can enter the name of the ingredient they want to remove in the same field they would use to add an ingredient. After that they can click on "Rem Ingredient" to remove it.

**Comment by ghost** [comment]
Work on this feature will continue during stage 3 until the desired user story is achieved.

**Comment by nathandinatale** [comment]
This feature can be done through the backend but there is currently no UI implementation.
