### ISSUE TITLE
Recipe Search Bar

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#5]
_From @niklasgutheil on February 8, 2017 19:59_

The user will be able to click the search bar and enter a recipe they would like to find from our database. 

_Copied from original issue: poisonctrl/G7#5_

**Comment by poisonctrl** [comment]
Assigned niklasgutheil per Slack #meetinglog

**Comment by ghost** [comment]
The user can click the search bar and enter the name of the recipe they would like to find from our database.

**Comment by ghost** [comment]
Work on this feature will continue during stage 3 until the desired user story is achieved.

**Comment by nathandinatale** [comment]
The user enters their search query into a static text box then clicks on the "Search by Recipe" button
