### ISSUE TITLE
Ingredient Search Bar

### ISSUE THREAD

**Issue by poisonctrl** [poisonctrl/FoodBookSQLDB#6]
_From @niklasgutheil on February 8, 2017 20:2_

The user will be able to search for recipes by starting to type and then a drop down menu of selected items will be available to choose from. 

_Copied from original issue: poisonctrl/G7#6_

**Comment by poisonctrl** [comment]
Added Niklasgutheil per request in Slack #meetinglog.

**Comment by ghost** [comment]
The user will first need to add the ingredient(s) they want to search the database by and then they can proceed to searching the database.

**Comment by ghost** [comment]
Work on this feature will continue during stage 3 until the desired user story is achieved.

**Comment by nathandinatale** [comment]
The user types into a static text box with no restrictions or drop down menu, which the database will be searched for.
